--------------------------------------------------------
--  파일이 생성됨 - 수요일-10월-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTENDANCE_MARK
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK" 
   (	"ATTENDANCE_CODE" NUMBER, 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"LECTURE_CODE" VARCHAR2(25 BYTE), 
	"WEEK_CODE" NUMBER, 
	"FIRST_CLASS" NUMBER, 
	"SECOND_CLASS" NUMBER, 
	"THIRD_CLASS" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LECTURE
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."LECTURE" 
   (	"LECTURE_CODE" VARCHAR2(25 BYTE), 
	"PROFESSOR_ID" VARCHAR2(15 BYTE), 
	"LECTURE_NAME" VARCHAR2(50 BYTE), 
	"CREDIT" NUMBER, 
	"WEEK_DAY" VARCHAR2(10 BYTE), 
	"START_TIME" VARCHAR2(4 BYTE), 
	"END_TIME" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"PROFESSOR_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFESSOR_LOGIN
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."PROFESSOR_LOGIN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."STUDENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"STUDENT_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_LECTURE
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" 
   (	"STUDENT_LECTURE_CODE" NUMBER, 
	"STUDENT_ID" VARCHAR2(20 BYTE), 
	"LECTURE_CODE" VARCHAR2(25 BYTE), 
	"LECTURE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT_LOGIN
--------------------------------------------------------

  CREATE TABLE "C##CAPSTONE_ADMIN"."STUDENT_LOGIN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into C##CAPSTONE_ADMIN.ATTENDANCE_MARK
SET DEFINE OFF;
REM INSERTING into C##CAPSTONE_ADMIN.LECTURE
SET DEFINE OFF;
Insert into C##CAPSTONE_ADMIN.LECTURE (LECTURE_CODE,PROFESSOR_ID,LECTURE_NAME,CREDIT,WEEK_DAY,START_TIME,END_TIME) values ('TEST1255','123412123','과목테스트',3,'WED','0900','1200');
REM INSERTING into C##CAPSTONE_ADMIN.PROFESSOR
SET DEFINE OFF;
Insert into C##CAPSTONE_ADMIN.PROFESSOR (ID,PW,PROFESSOR_ID,NAME) values ('test','test1234','123412123','테스트용');
REM INSERTING into C##CAPSTONE_ADMIN.PROFESSOR_LOGIN
SET DEFINE OFF;
REM INSERTING into C##CAPSTONE_ADMIN.STUDENT
SET DEFINE OFF;
Insert into C##CAPSTONE_ADMIN.STUDENT (ID,PW,STUDENT_ID,NAME) values ('tjdals0231','alfl02@!','201607009','홍성민');
Insert into C##CAPSTONE_ADMIN.STUDENT (ID,PW,STUDENT_ID,NAME) values ('Test','Test02@!','200000000','테스트');
REM INSERTING into C##CAPSTONE_ADMIN.STUDENT_LECTURE
SET DEFINE OFF;
REM INSERTING into C##CAPSTONE_ADMIN.STUDENT_LOGIN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ATTENDANCE_MARK_ATTENDANCE_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK_ATTENDANCE_CODE_PK" ON "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK" ("ATTENDANCE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LECTURE_LECTURECODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."LECTURE_LECTURECODE_PK" ON "C##CAPSTONE_ADMIN"."LECTURE" ("LECTURE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESSOR_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."PROFESSOR_ID_PK" ON "C##CAPSTONE_ADMIN"."PROFESSOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESSOR_PROFESSORID_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."PROFESSOR_PROFESSORID_UQ" ON "C##CAPSTONE_ADMIN"."PROFESSOR" ("PROFESSOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESSORLOGIN_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."PROFESSORLOGIN_ID_PK" ON "C##CAPSTONE_ADMIN"."PROFESSOR_LOGIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."STUDENT_ID_PK" ON "C##CAPSTONE_ADMIN"."STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_STUDENTID_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."STUDENT_STUDENTID_UQ" ON "C##CAPSTONE_ADMIN"."STUDENT" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT_LECTURE_STUDENT_LECTURE_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."STUDENT_LECTURE_STUDENT_LECTURE_CODE_PK" ON "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" ("STUDENT_LECTURE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTLOGIN_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##CAPSTONE_ADMIN"."STUDENTLOGIN_ID_PK" ON "C##CAPSTONE_ADMIN"."STUDENT_LOGIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ATTENDANCE_MARK
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK" ADD CONSTRAINT "ATTENDANCE_MARK_ATTENDANCE_CODE_PK" PRIMARY KEY ("ATTENDANCE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LECTURE
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" MODIFY ("LECTURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" MODIFY ("CREDIT" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" MODIFY ("WEEK_DAY" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" ADD CONSTRAINT "LECTURE_LECTURECODE_PK" PRIMARY KEY ("LECTURE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESSOR
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" MODIFY ("PROFESSOR_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" ADD CONSTRAINT "PROFESSOR_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR" ADD CONSTRAINT "PROFESSOR_PROFESSORID_UQ" UNIQUE ("PROFESSOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESSOR_LOGIN
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR_LOGIN" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR_LOGIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."PROFESSOR_LOGIN" ADD CONSTRAINT "PROFESSORLOGIN_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT" ADD CONSTRAINT "STUDENT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT" ADD CONSTRAINT "STUDENT_STUDENTID_UQ" UNIQUE ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_LECTURE
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" MODIFY ("LECTURE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" ADD CONSTRAINT "STUDENT_LECTURE_STUDENT_LECTURE_CODE_PK" PRIMARY KEY ("STUDENT_LECTURE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_LOGIN
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LOGIN" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LOGIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LOGIN" ADD CONSTRAINT "STUDENTLOGIN_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTENDANCE_MARK
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK" ADD CONSTRAINT "ATTENCANCEMARK_STUDENTID_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "C##CAPSTONE_ADMIN"."STUDENT" ("ID") ENABLE;
  ALTER TABLE "C##CAPSTONE_ADMIN"."ATTENDANCE_MARK" ADD CONSTRAINT "ATTENCANCEMARK_LECTURECODE_FK" FOREIGN KEY ("LECTURE_CODE")
	  REFERENCES "C##CAPSTONE_ADMIN"."LECTURE" ("LECTURE_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LECTURE
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."LECTURE" ADD CONSTRAINT "LECTURE_PROFESSORID_FK" FOREIGN KEY ("PROFESSOR_ID")
	  REFERENCES "C##CAPSTONE_ADMIN"."PROFESSOR" ("PROFESSOR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_LECTURE
--------------------------------------------------------

  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" ADD CONSTRAINT "STUDENTLECTURE_STUDENTID_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "C##CAPSTONE_ADMIN"."STUDENT" ("ID") ENABLE;
  ALTER TABLE "C##CAPSTONE_ADMIN"."STUDENT_LECTURE" ADD CONSTRAINT "STUDENTLECTURE_LECTURECODE_FK" FOREIGN KEY ("LECTURE_CODE")
	  REFERENCES "C##CAPSTONE_ADMIN"."LECTURE" ("LECTURE_CODE") ENABLE;
